### ISSUE TITLE
[FEATURE] <made some ui changes to checkmark button to make it look better>

### ISSUE THREAD

**Issue by ankitjangidx** [gis-ops/valhalla-app#104]
### What kind of feature you are suggesting?
![image](https://user-images.githubusercontent.com/100501722/223632224-6a20762a-9b19-4e78-aca1-1db2e5886267.png)
In the screenshot provided, it appears that the checkmarks button is lacking a border and there is insufficient spacing between this button and the adjacent one. This lack of visual differentiation and cramped layout could potentially result in accidental clicks, and thus could benefit from some improvements.

### Does it solve any problem?
![image](https://user-images.githubusercontent.com/100501722/223633515-c6652e00-9682-41cb-9595-5c60c4539c57.png)

I have made some improvements to the checkmarks buttons. Specifically, I have added a border and a radius to the buttons, and placed them within a flexbox to ensure they are always centered with respect to the border radius. These changes have effectively addressed the concern of accidental clicks, as the buttons are now more visually distinct and have adequate spacing between them.

**Comment by nilsnolde** [comment]
Na we're good as it is, thanks.
