### ISSUE TITLE
[BUG] fix: KeyboardEvent error in Isochrones/Waypoints/index.jsx

### ISSUE THREAD

**Issue by eshan-003** [gis-ops/valhalla-app#106]
### Description

The React keyboard Event used is causing an error:-
Error:-
![Screenshot 2023-03-08 13 25 20](https://user-images.githubusercontent.com/107420267/223654712-3e35ba39-243e-4e91-81b7-486fed596103.png)
Fix:-
![Screenshot 2023-03-08 13 25 28](https://user-images.githubusercontent.com/107420267/223654744-33418571-3a58-40c1-9381-447a91f91c82.png)

plz assign this issue to me.

**Comment by nilsnolde** [comment]
sorry, everything about this is wrong.. please read and then act
