### ISSUE TITLE
Add github logo linking to this repo

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#11]
most issues land over in valhalla/valhalla. maybe less if we include a link to this repo.

**Comment by georg-d** [comment]
For me – an ordinary user – it is absolutely natural that most issues land in valhalla: In https://valhalla.openstreetmap.de/ the only term appearing in the GUI is valhalla, while "valhalla-app" is mentioned nowhere, neither as rendered text the search would find, nor as text inside an image. If I click the logo on bottom left, the github project of valhalla is opened. If I click the fossgis logo of white box in top left, I land on https://fossgis.de/news/2021-11-12_funding_valhalla/ where no really clear & prominent indication is given that what I see in https://valhalla.openstreetmap.de/ is not Valhalla, but its client valhalla-app, while only the data provider is Valhalla.


Idea: In the white box in top left, the bottom row is mostly empty. Left of the fossgis logo, add something like "Calculations by Valhalla visualized by Valhalla App", maybe additionally "routing engine" and "web GUI" which makes it 2 lines but the relation of the 2 parts become even more clear, and both project names are links to the according github projects. Mockup: ![20220311 212047-Valhalla FOSSGIS Server Demo App](https://user-images.githubusercontent.com/45993293/157955669-5cf13a61-df27-4f68-9ea8-63524b2de5dc.png)
Code of mockup: `<div class="tr"><span class="custom-label">Calculations by <a href="https://github.com/valhalla/valhalla">Valhalla</a> visualized by <a href="https://github.com/gis-ops/valhalla-app/">Valhalla App</a>.</span><a target="_blank" href="https:/fossgis.de" rel="noreferrer"><img src="/static/media/fossgis.45306c38.png" class="pa2" alt="gisops_logo" style="height: 40px; vertical-align:middle;"></a></div>`

**Comment by nilsnolde** [comment]
Thanks @georg-d , idea 1 sounds good to me. What do you think @TimMcCauley ?

**Comment by TimMcCauley** [comment]
Yep, added it just then, thanks both!

**Comment by georg-d** [comment]
Looks clean and links work 👍
