### ISSUE TITLE
[FEATURE] Hide Height-Graph Button in the bottom, and show only when user has selected any destination or source.

### ISSUE THREAD

**Issue by inceptionabhishek** [gis-ops/valhalla-app#114]
### What kind of feature you are suggesting?

The height graph button is useful when we have selected any source and destination however if we don't select anything from the map and we still click on the button then it shows a blank rectangular div which I think is a bit out of context. Instead of showing the blank div, we can either show some text or pop-up to let the user know "how to use that feature(height graph)".

I think what we can do here is that if the user has not selected any points on the map, and tries to click on the height graph button then on the hover of the mouse button we can show them some text "what is this feature about or how to use it".

Like we have in the settings panel for showing info about costing options.
And we can disable the button click until the user has not selected any points that can have a height graph.

### Does it solve any problem?
It will help to overcome the confusions that might occur while using the height graph. It will also hide the unnecessary blank div when the user has not selected any points on the graph.

### Screenshots

If we have not selected any points on the graph: -

<img width="932" alt="image" src="https://user-images.githubusercontent.com/65409282/224229346-0947baa6-d4ac-4320-bb53-1f1ef7b5a59f.png">

It works fine when points are selected 👍 
 
<img width="856" alt="image" src="https://user-images.githubusercontent.com/65409282/224232392-05c8efbd-3f11-451b-9b1e-ca7638fe8e61.png">

**Comment by nilsnolde** [comment]
Yes that's true, it might be better to disable it and show a tool info when hovering (also show it when it's enabled). The icon is pretty on point, but still better to have it confirmed with text.

**Comment by inceptionabhishek** [comment]
Yeah, that would be better!
I will raise PR Soon for this. :)

**Comment by inceptionabhishek** [comment]
This issue is open for everyone, if they want to resolve this issue they can raise PR.

**Comment by nomandhoni-cs** [comment]
I was facing the same problem while clicking on the Heigh Graph button. I am already working on this issue, now I found out there is this issue already created in GitHub.
![Screenshot_53](https://user-images.githubusercontent.com/92979541/224992736-251b7f9d-331c-45cb-9041-2b1661857ccf.png)

## Ideas
- Idea 1: Show the button when 2 or more waypoints selected
- Idea 2: Show an alert when 2 or more waypoints are not selected.

@nilsnolde  @inceptionabhishek Any suggestions which idea will improve the user experience,

**Comment by inceptionabhishek** [comment]
@nomandhoni-cs Well, I my opinion you can show the text: "Height Graph" on mouse hover, and disable the icon till the user has not selected both waypoints. In your recent PR #126, you placed the text below the icon which I think looks gross. So, just make it hover text only. 
_Thanks_

**Comment by nilsnolde** [comment]
Not only waypoints have to be selected, an actual route has to be already computed.

IMO it's best to _disable_ (i.e. not hide) the button where there's no route.

**Comment by nabin-nath** [comment]
@nilsnolde I tried to use hide the button when there are less than two directions, and show if more than or equal to 2, but the issue i am facing is Map is defined in componentDidMount, i was using redux and setting true of false in the controlSetting of the map, as the Map is in componentDidMount it is rendering only once, can you suggest me a simple way to do it?

**Comment by Rohitkr2510** [comment]
I want to work on this issue. Please assign it to me.

**Comment by nilsnolde** [comment]
It’s done I think
