### ISSUE TITLE
[FEATURE] Tooltip for search box of Directions and Isochrones tab

### ISSUE THREAD

**Issue by MihirKp25** [gis-ops/valhalla-app#115]
### What kind of feature you are suggesting?
When users search for any destination, they get a variety of choices for a destination but cannot preview the full address when they have entered the destination. We can add a tooltip for the search box in both Direction and Isochrones tabs. This tooltip will show a small preview of whatever input is given in the search box. If nothing is given input we can disable input for that time.  

### Does it solve any problem?
It prevents from getting confusion for users because it may happen some time initial words of some addresses are almost the same and therefore it will be tedious for the user to check it by selecting it. Instead, we can show him/her a preview of input given directly.

### Screenshots

![image2](https://user-images.githubusercontent.com/106189515/224241091-1ec9724c-6c47-41e8-b19b-1863ad29956c.png)

### Additional information

I want to implement this feature as a part of my pre-GSOC work

**Comment by nilsnolde** [comment]
Jep, small UX improvements like that are appreciated, thanks.
