### ISSUE TITLE
[BUG] less padding between buttons 

### ISSUE THREAD

**Issue by Ananya2001-an** [gis-ops/valhalla-app#118]
### What is the problem you are facing
On the directions tab when searching for a place, the 2 buttons (tick and cross) have very less margin between them.

### What is your suggested solution
Adding a little bit of padding would be nice so that on hovering over the links users don't get distracted.

### Screenshots

![image](https://user-images.githubusercontent.com/55504616/224472977-924bcdbd-16f2-49da-87ef-9f84a8817679.png)

https://www.awesomescreenshot.com/video/15508755?key=87b68edcbf665c6f500b353f0a2bce98

**Comment by lord2anil** [comment]
I want to work on this issue, please assign me

**Comment by Ananya2001-an** [comment]
Hey @lord2anil I am not the maintainer. Soon one of them would assign it to you if it's accepted.

**Comment by nilsnolde** [comment]
Sure, thanks for the issue @Ananya2001-an.

**Comment by nilsnolde** [comment]
BTW, did you check your mails @Ananya2001-an? I tried reaching out, but maybe that was an older address. You want to contact me on my public email?

**Comment by Ananya2001-an** [comment]
> BTW, did you check your mails @Ananya2001-an? I tried reaching out, but maybe that was an older address. You want to contact me on my public email?

I have not got any mail from you. This is my current mail id: `ananyanayak102@gmail.com`

**Comment by Ananya2001-an** [comment]
Wait I just got the mail it was in my spam

**Comment by Ananya2001-an** [comment]
I just replied. 😊

**Comment by lord2anil** [comment]
I think we should increase the size also. see the image...
![image](https://user-images.githubusercontent.com/97228857/224566471-1a6dfba7-367c-4272-b34f-a2e170e2e262.png)

**Comment by Ananya2001-an** [comment]
> I think we should increase the size also. see the image...
> ![image](https://user-images.githubusercontent.com/97228857/224566471-1a6dfba7-367c-4272-b34f-a2e170e2e262.png)
> 

Looks great!

**Comment by nilsnolde** [comment]
Maybe a tiny bit smaller😄somewhere between right now and yours.

**Comment by lord2anil** [comment]
![image](https://user-images.githubusercontent.com/97228857/224566968-c85b023d-715c-4fe6-9a03-8d01e0b6d94b.png)
?
