### ISSUE TITLE
[BUG] Debounce Isochrone API calls when adjusting interval settings by dragging the sliders

### ISSUE THREAD

**Issue by wcedmisten** [gis-ops/valhalla-app#121]
### What is the problem you are facing
Currently when these sliders get adjusted by dragging them (not by clicking on a value), the frontend makes a request for each interval between the previous value and the new value. This results in the page lagging as the ~60 requests return sequentially and each redraw the polygon. This also puts extra strain on the server from this many requests being made in quick succession.

### What is your suggested solution
Adjusting the slider should not send a request with the new settings until the mouse click is released.

### Screenshots

![image](https://user-images.githubusercontent.com/4565200/224553489-50074f71-e7d8-4f51-a0d9-973bfe7b1849.png)

![image](https://user-images.githubusercontent.com/4565200/224553634-75e689c8-33f5-4173-8bb9-9fc052d74e00.png)

**Comment by nilsnolde** [comment]
Oh yes, good one!

**Comment by sandstone991** [comment]
Hello @nilsnolde you might remember me from my previous unannounced PRs, so I'm going to ask to be assigned first this time, can I work on this?

**Comment by nilsnolde** [comment]
Sure, thanks!
