### ISSUE TITLE
Change the issues template action

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#129]
### What would you like to share?

In #95 we added issue templates. I think that's a good thing, however, it'd be more legible if we didn't use `[FEATURE]` sort of prefixes. Ideally we'd let Github label the issue appropriately, which is much more pleasing visually.

**Comment by Ananya2001-an** [comment]
GitHub doesn't add labels automatically. Currently the issue template has the `labels` section with which it assigns a label to the issue.

**Comment by Ananya2001-an** [comment]
If we want we can remove it from the template so that we can add labels manually.

**Comment by nilsnolde** [comment]
I‘m pretty sure it’s possible to add labels via templates automatically. But we can get to that when we started the whole thing, it’s not really urgent:)

**Comment by Ananya2001-an** [comment]
Yeah in the issue template I have added the `labels` prop which should add a label as soon as someone creates an issue but it's not working for some reason which is weird. But you are right we can look into that later. 👍🏼

**Comment by hs7898753** [comment]
@Ananya2001-an  The issue with your YAML code is that the labels field should not be enclosed in single quotes. YAML uses square brackets [] to indicate an array, so you should enclose your label name in square brackets.

your code: labels: [🐛bug]
correct code : labels: [bug]

**Comment by hs7898753** [comment]
Yeah! Using double quotes is more useful to categorize issues based on multiple criteria.
