### ISSUE TITLE
[BUG] Overlay menu pushes the other leaflet controls down

### ISSUE THREAD

**Issue by suyashvsingh** [gis-ops/valhalla-app#132]
### What is the problem you are facing

When we hover over the Overlay menu toggle, the menu opens, but its pushes the other leaflet controls below it.

### What is your suggested solution

The overlay menu should not push the other leaflet controls down, instead it should open in-place. In addition to it, the size of the menu toggle should be same as of the other icons

### Screenshots

![Screenshot (6)](https://user-images.githubusercontent.com/80644262/225448504-1391f559-4ead-4ef5-a941-5ddc53d516ec.png)
![Screenshot (7)](https://user-images.githubusercontent.com/80644262/225448511-23543637-56c4-49f0-9912-0f5edf825a5b.png)

**Comment by suyashvsingh** [comment]
I would certainly like to work on this issue

Thanks

**Comment by nilsnolde** [comment]
> The overlay menu should not push the other leaflet controls down

Why not?

**Comment by suyashvsingh** [comment]
In my opinion, there is one major issue with the current implementation; If a user accidentally hovers, the menu opens, and on mouse leave, the menu closes. This is not the best experience, since all the components go up and down within a second. If the overlay menu is open in place, it would be far less distracting. This is the issue I faced when I was going through the App for the first time.

Suppose the current behaviour is the expected behaviour, then the overlay menu should open when the user **clicks** on it rather than **hover** because the user knows exactly what he/she is trying to achieve.

Regarding the size of the toggle, it should be the same as that of the other leaflet controls below it.

Any suggestion regarding the same would be highly appreciated. 

Thanks
