### ISSUE TITLE
[FEATURE] Feedback Mechanism

### ISSUE THREAD

**Issue by hs7898753** [gis-ops/valhalla-app#133]
### What kind of feature you are suggesting?

       Implementing a user feedback mechanism.

### Does it solve any problem?

       User feedback is a great way to understand how people are using the app, what they like and dislike, and what needs 
       improvement. With this, we can identify the most important issues and features to work on first.

**Comment by nilsnolde** [comment]
Hm that's what Github is for IMO. It's linked in the app, which should be enough. A feedback mechanism inside the app is over the top I fear. Or what is you're actually proposing?

**Comment by hs7898753** [comment]
Github is a great for bug reporting and technical issues, but it may not be the best option for gathering general feedback from users about their experience with the app. Having a feedback mechanism within the app itself can help to increase user engagement and make it easier for users to share their thoughts and suggestions. This  lead to a better understanding of user needs and an improved product.

**Comment by hs7898753** [comment]
IMO this may not be so important at this point of time.. But it can be useful to understand users general feedback

**Comment by Ananya2001-an** [comment]
@hs7898753 Are u saying that there should be some contact form sort of thing in the website?  I guess GitHub discussions is a good enough platform for that. We can maybe add a link to github discussions on the site if that's a favorable option? In form of a github icon which will also showcase that the project is open source. WDYT @nilsnolde ?

**Comment by hs7898753** [comment]
@Ananya2001-an it's true that linking to GitHub discussions is an excellent way to provide a platform for user feedback. Still, it's essential to consider that not all users may be familiar with GitHub and may not be comfortable using it to provide feedback. 
So, in my opinion, having a feedback mechanism within the app is a good option and it makes it easier for a user to provide their feedback.

**Comment by hs7898753** [comment]
Also, GitHub provides a platform for users to discuss technical issues and bugs, but it may not be the best option for gathering general feedback from users about their experience with the app.

**Comment by Ananya2001-an** [comment]
Your points are also correct.

**Comment by nilsnolde** [comment]
Yeah I’m with @Ananya2001-an, discussions was built exactly for that purpose, to use GitHub as a platform for non-technical issues, Q&A etc. Sure, needs a GitHub account, but that’s a much smaller price to pay than developing and maintaining a feedback mechanism of any sort. 

“Best” is relative IMO and a trade off of the project’s goals. Here the focus is mostly on low maintenance:)

**Comment by hs7898753** [comment]
Yah I agree with you that our focus is on low maintenance. That is why I already mentioned it earlier. This may not be so important at this point of time.
