### ISSUE TITLE
[FEATURE] Use User Feedback and Integrate weather forecast feature

### ISSUE THREAD

**Issue by Akshat171** [gis-ops/valhalla-app#138]
### What kind of feature you are suggesting?
we can add a Feedback form and integrate a weather forecast feature for all places. 

### Does it solve any problem?
Collecting user feedback is a great way to learn what is working well and what needs to be improved in your map application. Consider implementing a feedback system or survey to gather user feedback and make improvements based on that feedback Consider integrating a map application with another service that users may find useful, such as weather forecasts. This can add value to your map application and keep users engaged.

**Comment by hs7898753** [comment]
Weather conditions can change quickly and may not have a significant impact on the route or the user's travel plans.
but yes IMO it may be better to provide a weather forecast as an optional feature that users can access within the app, rather than integrating it into routing.

**Comment by Akshat171** [comment]
It can affect users' travel plans it provides valuable information to users about current and future weather conditions in a particular location. This information can be critical for making decisions related to travel, outdoor activities, and safety.

For example, if a user is planning a road trip, they can use the weather forecast to determine the best route based on current and predicted weather conditions. If there is a chance of severe weather, such as thunderstorms or heavy snowfall, users can adjust their travel plans accordingly.

**Comment by hs7898753** [comment]
I agree with your point. But, integrating weather forecasts into routing may not always be necessary. Ex. if a user is only traveling a short distance, weather information may not impact their route or travel plans significantly. Moreover, integrating weather forecasts into routing may increase the complexity of the app, making it harder for users to use and navigate.

Therefore, providing a weather forecasts as an optional feature that users can access within the app is a better approach. 
WDYT @nilsnolde

**Comment by nilsnolde** [comment]
Even though you’re right, integrating weather forecast is nice and even nicer to actually include it in the routing algo as costing instead of pure informational as a visual layer, this is a bit over the top for now. This is still mostly a demo app for a routing engine we maintain. In case it should ever go further than that, we can consider this, similar to #133.

**Comment by Akshat171** [comment]
@hs7898753 this application is not for the user who going to travel short distances. we have to think from both point of view so I think it is the common or main feature of every map application.

**Comment by Akshat171** [comment]
@nilsnolde Please review this feature, is there anything I can improve on?

**Comment by Pratham271** [comment]
We can also suggest the alternate route if the weather is too bad at the primary route as we are already adding the weather forecast condition
