### ISSUE TITLE
Reset of profile settings to default values

### ISSUE THREAD

**Issue by georg-d** [gis-ops/valhalla-app#14]
In the GUI, please allow to quickly +easily reset a single or all settings (driveway factor, step penalty,...) to default values. Example use cases

- You changed settings for a very specific, untypical trip, e.g. with your visiting grandpa in his wheelchair or 2 year old nice, and now you'd like to compute a route for yourself with "normal" settings
- You experience a weird routing result like https://github.com/valhalla/valhalla/issues/3573 and would like to rule out that it is caused by a setting you unintetionally changed to a weird value

**Comment by TimMcCauley** [comment]
This is a good idea @georg-d - I'll implement a reset button.

**Comment by TimMcCauley** [comment]
I added both single and global reset functionality in 7d496515f555c5809b754304660f54f58a672ea4
