### ISSUE TITLE
Modify the customSlider handle change function

### ISSUE THREAD

**Issue by andreyscott** [gis-ops/valhalla-app#141]
### Additional information

 const handleChange = (value) => {
      //reset
      switch (true) {
        case isNaN(value):
          value =
            profile === 'truck'
              ? settingsInitTruckOverride[option.param]
              : settingsInit[option.param];
          break;
        case value < min:
          value = min;
          break;
        case value > max:
         value = max;
          break;
        default:
        break
      }
    
      setSliderVal(parseFloat(value));
    
      debounce(
        300,
        handleUpdateSettings({
          name: option.param,
          value: parseFloat(value),
        })
      );
    };

**Comment by DevMarioNan** [comment]
can you sign me to do it?
