### ISSUE TITLE
Route shown even if waypoint input is altered

### ISSUE THREAD

**Issue by Ananya2001-an** [gis-ops/valhalla-app#144]
### What is the problem you are facing
Right now when we change the input of any waypoint, the route is still shown.

### What is your suggested solution
Any change made to input should remove the route automatically just as what happens when we click the cross icon to remove the waypoint manually.

### Screenshots

https://user-images.githubusercontent.com/55504616/227126913-7ffca138-cc71-45cc-a84b-65fffc6f6dd3.MOV

**Comment by nilsnolde** [comment]
Yeah that's true. I felt like maybe that's a little disturbing to remove the route on _every_ change, but it's what Google Maps does as well. Obviously I don't like GM, but they did spend millions on UX, so let's trust that:)

**Comment by Ananya2001-an** [comment]
Yeah sure! Wait for one of the maintainers to come and assign this to you.

**Comment by Ananya2001-an** [comment]
> @Ananya2001-an Can you check the pr? I mean that's how you wanted it to work right?

Sure I will review it.
