### ISSUE TITLE
[FEATURE] Automation of Search Box Suggestion

### ISSUE THREAD

**Issue by hs7898753** [gis-ops/valhalla-app#145]
### What kind of feature you are suggesting?
  Currently to see suggestion we have to click tick button. It would be more good if search box provide with suggestions automatically. 

### Does it solve any problem?
When I change my location in the search box, the suggestions donot update automatically with my typing. Instead, they only update when 
I click on a tick button. This is causing inconvenience and making it 
difficult for me to find the information I am looking for. 

### Screenshots

![searchBoxUpdate](https://user-images.githubusercontent.com/112114562/227131756-0f16ad0e-b7fc-49a1-9af0-0b92e8de5d55.png)

**Comment by nilsnolde** [comment]
Yeah I know, it's unfortunate, but that's the limitation of Nominatim, the geocoding engine we use to turn addresses into locations. It doesn't support autocomplete and it's against the ToS to use it like that (which is kinda not possible anyways, autocomplete query algorithms behave very differently from "normal" search algorithms).
