### ISSUE TITLE
[BUG] No option to remove drawn polygon

### ISSUE THREAD

**Issue by Rohitkr2510** [gis-ops/valhalla-app#148]
### What is the problem you are facing
The map provides an option to remove the last vertex of a polygon, but there is no option available to remove an entire polygon or multiple polygons once they have been drawn.
### What is your suggested solution
Please add an option to the map that allows for the removal of entire polygons or multiple polygons after they have been drawn.

### Screenshots

![Screenshot (140)](https://user-images.githubusercontent.com/95642350/227186087-b6b39bf6-10a5-43f2-8ee9-d78d271a249d.png)

**Comment by nilsnolde** [comment]
@bibhestee is correct, it's already there.
