### ISSUE TITLE
[BUG] Infinite map scroll

### ISSUE THREAD

**Issue by Ananya2001-an** [gis-ops/valhalla-app#151]
### What is the problem you are facing
Right now the map continues indefinitely repeating the same areas but without markers. 

### What is your suggested solution
We can solve this in 2 ways:

1. Either have just 1 section of the map showing the whole world with the markers. For this I believe we will need to look into leaflets map bounds properties to manage how far out the zoom can go (prevent gray area) and the infinite horizontal scroll.

2. Or have the routes repeating as well as we scroll the map further. This is what GM follows too. @nilsnolde I know you hate GM so let's follow the first one then if you approve 😆 

### Screenshots

https://user-images.githubusercontent.com/55504616/227539052-7fa220a0-1311-459e-8d9c-3008989c523e.mp4

**Comment by nilsnolde** [comment]
Haha yeah, either way I think 1. could be better;) Though 2. is nicer for the user. Will depend probably on how the code-changes-to-UX tradeoff looks like, I'd still investigate both tbh.

**Comment by hs7898753** [comment]
https://user-images.githubusercontent.com/112114562/227711694-5559defd-02a5-488f-a846-14c9a9b60bd7.mp4

How is that?

**Comment by Ananya2001-an** [comment]
> https://user-images.githubusercontent.com/112114562/227711694-5559defd-02a5-488f-a846-14c9a9b60bd7.mp4
> 
> How is that?
> @nilsnolde @Ananya2001-an 

It looks good! 👍

**Comment by hs7898753** [comment]
Should I raise PR our is there any other change we require to do
