### ISSUE TITLE
Adding share location feature

### ISSUE THREAD

**Issue by Akshat171** [gis-ops/valhalla-app#157]
### Description
share location feature
### What kind of feature you are suggesting?
Adding location sharing button
### Does it solve any problem?
The share location feature in a map application allows a user to easily share their current location with others. 

### Additional information
When a user clicks on the share location button in the map application, the application will request the user's current location using the HTML5 Geolocation API. Once the location is obtained, the application can either display the location on the map or generate a shareable link or code that can be sent to others.

_No response_

**Comment by nilsnolde** [comment]
IMO this is not so interesting for us. However, #156 is actually going in a similar direction. Not for sharing purposes (out-of-scope for us), but to zoom the map to the user's location if desired.
