### ISSUE TITLE
[BUG] Current Isochrones tab enhancement

### ISSUE THREAD

**Issue by Sheikh-JamirAlam** [gis-ops/valhalla-app#162]
### What is the problem you are facing
The current Isochrone tab looks like this. "Visualized with Valhalla App" at the end is getting cut off due to the width of the tab. Also the Directions tab and the Isochrone tab should be of same width, I think that would make more sense UX wise.

### What is your suggested solution
Keeping the width of Directions tab and Isochrone tab same. 

I would like to work on this issue, if possible.

### Screenshots

![image](https://user-images.githubusercontent.com/48979376/228570368-d56abd0e-7e41-4c79-b9e6-0236ea085b33.png)

**Comment by tommach591** [comment]
I do think that the Isochrone tab should be bigger in width, but matching the width with the Directions tab might be difficult because the Directions tab increases in width as you add more waypoints. This is because each waypoint is numbered, as the number increase in digits, so will the width.

**Comment by Sheikh-JamirAlam** [comment]
@tommach591 You are right when the number of waypoints increases the width of the tab changes. But I think the width change like this is kind of weird.
Leaving the directions tab for now, how about I just increase the width of Isochrones tab a bit for now. The "Valhalla App" text should appear clearly and also I noticed the input search field is not vertically centered with the delete button. Maybe I can start fixing that?
![image](https://user-images.githubusercontent.com/48979376/228744122-bc3ef25f-6989-483d-96b9-c69152ff145e.png)

**Comment by nilsnolde** [comment]
Sure, would be appreciated, thanks. I wouldn't put too much in there for now. At some point we'll need a different layout once we want to add different endpoints for e.g. map-matching & optimized routes.
