### ISSUE TITLE
Text autocompletion at search box [FEATURE]

### ISSUE THREAD

**Issue by harsh5902** [gis-ops/valhalla-app#165]
### What kind of feature you are suggesting?
On search box 
![image](https://user-images.githubusercontent.com/74867899/229267147-96f94f96-0c8f-4846-b312-f39ac33e7f87.png)
autocompletion of the names of places or location.

### Does it solve any problem?
Currently IMO not too in much of a need, but thought should metion the idea😅

**Comment by hs7898753** [comment]
This was already mentioned earlier #145

**Comment by harsh5902** [comment]
oh okay I didn't notice 😅
