### ISSUE TITLE
Enhance OpenStreetMap's functionality by adding weather forecast for searched cities.

### ISSUE THREAD

**Issue by spyatmycode** [gis-ops/valhalla-app#167]
### What kind of feature you are suggesting?

Providing users with additional information that can be useful when planning a route or exploring an area.
I'm suggesting a two day weather forecast for the searched location which can easily gotten by using a free weather API.

The weather info will be shown just before the "MEMBERS" section on the result of the searched city.

All of the above will be implemented on the Side Bar.

### Does it solve any problem?

By having weather forecast information available in the sidebar, users can quickly see what the weather will be like in the area they are interested in and plan accordingly. This can be especially important for outdoor activities or when traveling to new locations.

### Screenshots

<img width="1440" alt="Screenshot 2023-04-02 at 09 03 50" src="https://user-images.githubusercontent.com/95282550/229341175-8551444f-fd30-428e-bb6e-0f0527ab52e1.png">

### Additional information

I have implemented something similar while using Map Box. However the weather info is optional. The use clicks on an icon on the location pop up to view the weather info.

**Comment by nilsnolde** [comment]
Wrong repository..

But I can say that both, for this project and the one you want to contribute to (openstreetmap.org), we wouldn’t like smth like that. It’s too easy to look up on a mother website.
