### ISSUE TITLE
download shall contain metadata shown on website, e.g. all navigation points, directions/maneuvers, maybe settings and server info

### ISSUE THREAD

**Issue by georg-d** [gis-ops/valhalla-app#17]
Calculate any route at [valhalla.openstreetmap.de](https://valhalla.openstreetmap.de/) and you will get a window "Directions" where you can click "Show Maneuvers" and get instructions like these 
![Valhalla 20220324 routing instructions on the website](https://user-images.githubusercontent.com/45993293/160297734-cfe37e96-d0ac-476a-ad23-ae85ce3c1809.png)
If you click "Download" just above the directions and besides to "Show Maneuvers", a GeoJSON is downloaded but it does only contain the pure dot list = way, but not any metadata. What metadata do I think of?

- I heavily miss the navigation points, i.e. start, end, if existing any via points. They help to tell apart several downloaded routes. To my limited understanding of [GeoJSON spec](https://datatracker.ietf.org/doc/html/rfc7946#section-6), this is easily possible by adding a member `properties` to all navigation points, with sub-members like e.g. `name` (e.g. _"L5010, Einöd, Gemeinde Herzogenburg, Bezirk St. Pölten, Niederösterreich, 3130, Österreich"_) and `role` (any of "start", "via", "target"). If you know _one really widely understood_ standard for that in GeoJSON, let's use that one instead of inventing yet another format :-) In a time boxed research, I did find several standards, e.g. [apidocs.geoapify.com](https://apidocs.geoapify.com/docs/routing/#api-outputs) which seems to be – to my limited understanding of GeoJSON – a proper GeoJSON extension. 
- I heavily miss distance, duration, mode of transportation. They help to tell apart several downloaded routes, but also to quickly get an idea whether a route is feasible for available time & energy.
- I heavily miss directions/maneuvers shown on website. They are important to enable humans to "execute" the route, but also for further processing like estimating/visualizing remaining time & distance. Same as above for standards. If you do not know one widely used one, we can IMHO just recycle the format delivered to the website, or use any of the standards, e.g. apidocs.geoapify.com uses
`"steps": [{
		"from_index": 0,
		"to_index": 1,
		"distance": 55,
		"time": 5.71,
		"instruction": {
			"text": "Drive southeast on Avenue Jacques Georgin."
		}
	}, {
		...
	}
]`
- I moderately miss settings like penalties for certain way types. They can be helpful to tell apart if you use different settings (e.g. cycling with your small kids versus cycling with your racing club mates), for debugging and for support requests (e.g. understanding why a steep hill is or is not used by bicycle mode). This seems to be easy to implement as there already is a serialization behind "Copy Settings to Clipboard" button.
- I slightly miss it, but for debugging and support requests, the following could be useful as they make clearer how to reproduce: URL to re-generate this route. Generation time and server and software version.

**Comment by nilsnolde** [comment]
wouldn't think the download option is so heavily used:) a few comments:
- I think generation time and server version would be nice to have, jep
- similarly it'd be pretty easy to export the current settings as a JSON property
- most points you raise are available in the raw valhalla response, so it could be an option to have a menu showing up on "Download" for raw & GeoJSON. raw won't be a GeoJSON though, but a raw valhalla JSON response. that's the easiest way of doing what'd you'd like to see. the harder way would be what you're suggesting: parse valhalla's raw response into a GeoJSON. AFAIK most GIS software won't gracefully deal with complex `properties` values like objects and arrays, so it's of limited use to force the response into a GeoJSON format IMHO

really GeoJSON spec is very simple and only deals with very few requirements. the "standards" that you mention don't exist and geoapify just does their own representation of a valhalla reponse which is not used by any other provider. still, that'd be a great starting point of course if one chooses to go down the harder path.

if you want to take a stab at this in the react app, let us know, we can surely give some directions.

**Comment by georg-d** [comment]
Thank you for your brain food 🙂 

If no-one comes up with a widely used standard for GeoJSON with turn-by-turn-commands, we must convert anyway to whatever GeoJSON variant we need, so it does not matter what JSON we use as base. Then it's pretty user friendly to allow downloading raw server response (already includes the first 3 bullet points of initial request) and GeoJSON (pure line), both enriched by generation time stamp, Valhalla version and settings.

Download feature heavily used? _Not yet_ by me, but I did few tries with downloadad Valhalla routes because Valhalla-App is one of the few router GUIs that allow longer routes _and_ rather detailed settings (e.g. hiking sac scale 1...6 or car max speed 80km/h due to a trailer) which makes it a very attractive alternative to others: 

- [BRouter](http://brouter.de/) and [OsmAnd built-in routing](http://osmand.net/features/navigation) allow rather detailed settings but calculation time strongly increases with route distance. 
- [GraphHopper's web GUI](https://graphhopper.com/maps/) does not expose the API's configuration possibilities, same applies to GUI in Android app "Locus". 
- [YOURS](https://wiki.openstreetmap.org/wiki/YOURS) does not allow any detailed settings. 
- [ORS](https://maps.openrouteservice.org/) offers a lot of profiles but few settings, so e.g. hiking SAC scale 4 can't be configured.

**Comment by TimMcCauley** [comment]
I added the raw JSON functionality in c86f0c1a3dc64acd64940990325bd3247a6acd3a
