### ISSUE TITLE
Part of the Height graph being cut off

### ISSUE THREAD

**Issue by Sheikh-JamirAlam** [gis-ops/valhalla-app#177]
### What is the problem you are facing

Some part of the Height graph is getting cut off because of the settings panel due to its width. I know we can adjust it later by just draging edges but it would be nice if it was visible readily.

https://user-images.githubusercontent.com/48979376/230570684-8ed13685-b47e-411e-98a7-7640aca1adb7.mp4

### What is your suggested solution

I suggest to make the height graph fully visible when button is clicked.

**Comment by nilsnolde** [comment]
Yeah I think so too. You can try again @Sheikh-JamirAlam with current master and re-open if it's not solved yet.
