### ISSUE TITLE
in context menu, color code the coordinate format Valhalla understands

### ISSUE THREAD

**Issue by georg-d** [gis-ops/valhalla-app#21]
In context menu (after click into map), the two coordinate formats _lat, lon_ and _lon, lat_ are offered. Most software including Valhalla do only unserstand _Latitude, Longitude_ so please color code that format in green and/or make the other visibly lighter grey, so users are more likely to use the "usually working format". 

Because I do not see _lon, lat_ much used, IMHO we could replace it with another widely spread format, i.e. 37° 13' 49.1808'' N 18° 21' 27.6732'' E

**Comment by TimMcCauley** [comment]
It really depends on the software which is why I wouldn't want to make any assumptions regarding the "usually working format".
