### ISSUE TITLE
How can i enable the Matrix API?

### ISSUE THREAD

**Issue by Uranbold** [gis-ops/valhalla-app#215]
### What would you like to share?

I'm newbie and i need to enable Matrix API on my local Demo. Is there are any guide or I'm missing something?

**Comment by nilsnolde** [comment]
there's nothing you have to do.. why do you think it's "not enabled"? if you get some error on `/sources_to_targets` POST request, it's more likely that your graph didn't build properly and/or your request is ill-formed.

**Comment by Uranbold** [comment]
@nilsnolde Thank you for your answer. I'm trying to understand How to display more than 1 result on the map.

The current demo is displaying & calculating the 1 Route result on Map. Trying to build at least 2 or 3 options. What should I do? I'm a newbie here sorry for my stupid questions.

**Comment by Uranbold** [comment]
Oh i see it's called the Alternates. I've been trying to display the alternates more than 2 or 3. API returning only 1.

**Comment by nilsnolde** [comment]
I don’t really understand what the problem is but it seems to me it has nothing to do with this repository. Try to read the Valhalla docs and open a discussion there if you still don’t get it
