### ISSUE TITLE
Option to add location as start/via/target point in location popup menu (map left click)

### ISSUE THREAD

**Issue by georg-d** [gis-ops/valhalla-app#22]
In context menu (after click into map), we can copy coordinates and afterwards paste them into 1 (i.e. from/start) or 2 (i.e. target/desination) or via points. It would be more convenient if context menu would offer to _directly set_ that location as start/via/target.

**Comment by TimMcCauley** [comment]
I think this is a good idea, this would then be a more sophisticated right click which now allows you to use as start/via/destination. What currently also does not work is to copy paste coordinates directly into the waypoints inputs which would be very handy. What do you think?

**Comment by nilsnolde** [comment]
>  It would be more convenient if context menu would offer to directly set that location as start/via/target.

Either I'm not understanding it or it was implemented after this issue, but the right-click is giving you exactly those options, no? Please re-open if I didn't understand it right and clarify
