### ISSUE TITLE
Update available costing options

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#32]
We should update this app soon. We got a few more costing options merged recently.

**Comment by nilsnolde** [comment]
@chrstnbwnkl , the latest when we add your `lit` PR to Valhalla, we'll take care of this. That one I'd definitely like to include in the web app:)

**Comment by ayush4345** [comment]
Hello, can you tell me where I have to add costing options in the web app ?

As I am not able to find costing options on the website as of now.

**Comment by nilsnolde** [comment]
It’s what you see in the right panel, the input to Valhalla. That’s all the context you’ll need, the rest is research.

**Comment by hs7898753** [comment]
Please Assign me this issue.

**Comment by nilsnolde** [comment]
Should we start by listing the missing costing options?

**Comment by hs7898753** [comment]
Yah! Sure

**Comment by hs7898753** [comment]
How to decide where to keep which costing option in Extra Settings or General Settings?
Ex: for bss_return_cost for Bicycle

**Comment by nilsnolde** [comment]
if smth is generally being used by many costing models, we keep it in general settings, if it's model-specific, e.g. `bss_return_cost` then it goes into the extra settings.

**Comment by hs7898753** [comment]
In the API reference PEDESTRIAN COSTING OPTIONS include (bss_rent_cost and bss_rent_penalty) which are bicycle costing options. should I add these options to Pedestrial or not?

**Comment by nilsnolde** [comment]
How do you know it’s for bike? Could be, I’d need to check the Valhalla code. bss stands for bike share station. It’s a multimodal concept of ped & bike, but doesn’t have its own costing. So options for bss can show up on both costings. 

In fact, you can disregard the bss stuff for the PR. We don’t support that yet anyways in the web app.
