### ISSUE TITLE
Is your map really calculate routes for trucks?

### ISSUE THREAD

**Issue by jnjdev42** [gis-ops/valhalla-app#47]
I would like to know if your map really calculate routes for trucks. And will avoid tunnels that are not allowed to trucks?

**Comment by nilsnolde** [comment]
> your map really calculate routes for trucks

This project is merely dockerizing https://github.com/valhalla/valhalla. But yes, of course, it's _really_ routing trucks.

> And will avoid tunnels that are not allowed to trucks?

If it's tagged properly in OSM, sure. Do you have an example where it's not doing that?

**Comment by nilsnolde** [comment]
Lacking feedback.
