### ISSUE TITLE
Prevent zooming out on short routes

### ISSUE THREAD

**Issue by chrstnbwnkl** [gis-ops/valhalla-app#48]
When calculating routes between points that are not far from each other, the map view always zooms out, so that the route becomes way to small to see.

**Comment by nilsnolde** [comment]
Thanks for actually not being too lazy to file an issue for that PITA :)

**Comment by chrstnbwnkl** [comment]
It just kind of annoys me that it does that. :D Looking at the source, it seems there was an intention:

https://github.com/gis-ops/valhalla-app/blob/7a888fb1bcb43d96a8e91d920684ca0c80a7bafc/src/Map/Map.jsx#L418

Mind if I just get rid of `maxZoom` here? If there's a new route, why not zoom into it even if it's a short one, or am  I missing something?

**Comment by nilsnolde** [comment]
It does annoy me too, but didn’t cross the threshold yet;) 

Definitely zoom in on new routes/isochrones! Sounds weird to limit it 11. If there was intention, a comment would’ve helped. Since there are none, let’s remove it and see, I’d say.
