### ISSUE TITLE
Remember map extent

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#50]
We should do the same as most map apps and remember the last extent when visiting the website. It's safe to just put it in the local browser store IMO. Smth we might want to do for more info than just extent, e.g. last used costing model?

**Comment by aa98-45556443355666** [comment]
I want to work on this issue for GSOC 2023. Kindly assign to me.

**Comment by nilsnolde** [comment]
Sure, once you put a PR, we can review.

**Comment by aa98-45556443355666** [comment]
ok I got it.

**Comment by hs7898753** [comment]
Hi, I want to work on this issue please assign it to me

**Comment by nilsnolde** [comment]
@aa98-45556443355666 we're open now, feel free to start and follow our guidelines: https://github.com/gis-ops/valhalla-app/wiki/GSoC-2023

**Comment by aa98-45556443355666** [comment]
#87

**Comment by aa98-45556443355666** [comment]
I will add a fresh pull request which will solve this problem also. [https://github.com/gis-ops/valhalla-app/issues/85](url)

**Comment by nilsnolde** [comment]
Let’s give others a chance

**Comment by aa98-45556443355666** [comment]
Please assign this issue to  me.

**Comment by inceptionabhishek** [comment]
@nilsnolde I want to take this issue. I have already raised a similar issue recently. #85

**Comment by aa98-45556443355666** [comment]
**@nilsnolde**  Its been more than 4 days that nobody has assigned this issue. Its  my humble request to assign this issue to me as I have   implemented the feature to remember map extent.

**Comment by nilsnolde** [comment]
I tried telling you in the previous PR, where you just sold someone else's work as your own, that it's not the way. We already have tons of applicants who keep me quite busy (compared to other projects I'm mentoring), so we can be a bit stricter here and I can tell you that we'll go with someone else. It's not like people don't deserve second chances, but also there's other GSoC projects, so I suggest you focus on smth else and just take this as a lesson.
