### ISSUE TITLE
Have the sidebar content extend vertically all the way

### ISSUE THREAD

**Issue by chrstnbwnkl** [gis-ops/valhalla-app#53]
Currently the sidebar content does not use the full viewport height, which becomes a problem when geocode results are displayed (see image: the lower ones disappear).
 
<img width="350px" src="https://user-images.githubusercontent.com/58629404/216447634-e45bdc4f-ef8e-43b6-8733-37877d335553.png" />

There's probably two things we should do here: 
  1. Have sidebar make use of the available height
  2. increase z-index of the geocode suggestion list

**Comment by Ghat0tkach** [comment]
hello ,I am completely new to the open source and would like to contribute in this issue .

**Comment by nilsnolde** [comment]
Sure, you can PR whenever you're ready, we'll review then.

**Comment by Ghat0tkach** [comment]
Am I supposed to increase the sidebar height?? like in the below example??

![219890086-81383989-2ef1-4b63-a6cb-9a5b7be05406](https://user-images.githubusercontent.com/59855919/219891643-63b8c02d-ca7c-44b7-bd17-1b9d44ab973c.png)

**Comment by nilsnolde** [comment]
I think that looks good:) You can just PR and then @chrstnbwnkl and me can take a look.

**Comment by Ghat0tkach** [comment]
I guess we shall close this issue as completed.
