### ISSUE TITLE
Include OSM link somewhere

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#54]
For debugging it'd be super helpful if we could quickly switch to openstreetmap.org. 

For now, it'd be enough (for me) to have a tool button in the right vertical toolbar to just switch to (more or less) the same map extent on osm.org. We get a lot of issues with links of our web app where we'd like to see the tagging quickly.

Eventually we could add a button in the Directions dialog to generate the same route on osm.org, but less of a priority.

Also, it'd be cool to optionally issue a locate request in the left-click menu to jump to the first way's OSM link.

**Comment by Bhavil-Ahuja** [comment]
Please assign this issue to me!

**Comment by mukul314** [comment]
Hey @nilsnolde ! Can you assign this issue to me? It's been over a week since this isssue has been assigned.

**Comment by nilsnolde** [comment]
Fair enough..

**Comment by harsh5902** [comment]
I know @nilsnolde you assigned this issue to @mukul314  but it has been more than 2 weeks so I resolved the issue and created PR.
