### ISSUE TITLE
Show tileset age

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#56]
We should also highlight somewhere how old the data is. It's always +/- 2 days, but people don't necessarily know that. Simply a request to `https://valhalla1.openstreetmap.de/status`

**Comment by tommach591** [comment]
Is this issue still open? I would like to work on it for GSoC if I can.

Something like this? 
![Capture](https://user-images.githubusercontent.com/57111473/223284306-e826a202-7cf3-4d35-bf71-df1182bd3727.PNG)

**Comment by nilsnolde** [comment]
Jep, exactly, smth like that. I'd left-align it and use ISO format for the date (not the dumb US format ;)). The caption should rather say "Last Data Update: xxx"

**Comment by tommach591** [comment]
How is this?

![Capture](https://user-images.githubusercontent.com/57111473/223371085-40f4be94-87af-44ab-9952-78e56bfb2b06.PNG)

**Comment by nilsnolde** [comment]
Ah sorry, I didn't mean the verbatim ISO format. `2023-03-06, 10:56` would be perfect, second resolution not needed.

**Comment by tommach591** [comment]
There we go.

![Capture](https://user-images.githubusercontent.com/57111473/223540655-f6d1230b-a33c-4284-aa7d-b93f6c3d34f0.PNG)

**Comment by nilsnolde** [comment]
Great, best to PR. Thanks.
