### ISSUE TITLE
Inconsistent height graph coloring

### ISSUE THREAD

**Issue by chrstnbwnkl** [gis-ops/valhalla-app#57]
https://valhalla.openstreetmap.de/directions?profile=bicycle&wps=13.376197814941408%2C52.547776790183214%2C13.38589668273926%2C52.55713840780446%2C13.393707275390627%2C52.5650153081717%2C13.390789031982424%2C52.56655304975672%2C13.389244079589846%2C52.57029962885746

In many cases, elevation change and steepness are contradicting, see this example:
![grafik](https://user-images.githubusercontent.com/58629404/217190900-1fecb149-e5af-4e8f-b412-633d3a5efe19.png)

**Comment by nilsnolde** [comment]
Yeah thanks for finally opening it:) Though I'm not sure if we're the problem or the upstream elevation diagram repo: https://github.com/GIScience/Leaflet.Heightgraph. The only other implementation of it I know is in https://classic-maps.openrouteservice.org and they don't show colors.

**Comment by hungerburg** [comment]
Here a shorter journey, from the train station to the hospital - https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=11.249715685844423%2C47.28104865174184%2C11.24449610710144%2C47.2835305523123

The "type 0" segment in the center does 80m ele over 250m distance, ~30% incline.

**Comment by aa98-45556443355666** [comment]
I want to work on this issue. Kindly assign it to me.

**Comment by Binabh** [comment]
hello maintainers,
I was trying to figure out a solution in order to ask to be assigned to this issue and found a possible solution and have created a pull request.
I would like to be assigned the issue and work on it.
Thank You!
