### ISSUE TITLE
"Public transport" mode

### ISSUE THREAD

**Issue by MarLoi** [gis-ops/valhalla-app#59]
Would it be possible to integrate the application with Transitland data? To add the "public transport" option.

**Comment by nilsnolde** [comment]
dup of #3 

We're in the process of removing support for transit.land in upstream Valhalla actually, to ingest raw GTFS. Will take another few weeks for the beta version to work. Hoping it'll be enough to integrate it in the public Valhalla instance and only then we'll implement it here in this web app.
