### ISSUE TITLE
Sign-up button stays disabled during 3rd party sign-up

### ISSUE THREAD

**Issue by Ghat0tkach** [gis-ops/valhalla-app#60]
When we try to log in using Google , if we use a name which is already taken , the error still persists even after the name is changed. 
and sign-up button also stays disabled

![image](https://user-images.githubusercontent.com/59855919/218326108-0226cdbb-757f-441b-92e3-e1f63e87f8fa.png)

**Comment by nilsnolde** [comment]
Hä?! What sign up button? Looks like openstreetmap.org? We’re on https://valhalla.openstreetmap.de.

**Comment by Ghat0tkach** [comment]
oh i am sorry
