### ISSUE TITLE
Route summary reporting error

### ISSUE THREAD

**Issue by blbal** [gis-ops/valhalla-app#61]
In the "Distance" box of a driving route a time of 22 min 43 sec is calculated.
The "Route Summary" on the map when the mouse is over the route shows this as 1h 22 min.

Difficult to describe in words so see the attached screen grab.

![screenshot_20230218_215159](https://user-images.githubusercontent.com/96541723/219901261-d0f99c81-cca9-4e35-8024-2055b6e426ae.png)

**Comment by Rohitkr2510** [comment]
Is this issue still open? I want to work on this issue.

**Comment by nilsnolde** [comment]
Nope, it's solved already, just needs some review by us: https://github.com/gis-ops/valhalla-app/pull/62

**Comment by Rohitkr2510** [comment]
Can you suggest some issues on which I can work?

**Comment by nilsnolde** [comment]
E.g. https://github.com/gis-ops/valhalla-app/issues/41?

May I ask the motivation? Just generally or to prepare for GSoC?

**Comment by Rohitkr2510** [comment]
To prepare for GSoC 2023.

**Comment by Devang0907** [comment]
can i get this  issue for solving?

**Comment by nilsnolde** [comment]
You can read right?

**Comment by Devang0907** [comment]
sorry, i mean how to start solving?

**Comment by nilsnolde** [comment]
https://github.com/gis-ops/valhalla-app/issues/81#issuecomment-1454026867

**Comment by Anmolgaur7** [comment]
Is this  issue still open ??
