### ISSUE TITLE
Remove default via waypoint

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#63]
When the app loads, we should remove the via waypoint by default. It should just show origin & destination.

**Comment by Ghat0tkach** [comment]
hey may i get to know some insights , when the app loads , we have 3 waypoints by default . So am i supposed to remove the extra  way point??

**Comment by cakepineapple** [comment]
Is this issue still open? I would like to fix this if yes.

**Comment by Devang0907** [comment]
can i get this issue for solve?

**Comment by nilsnolde** [comment]
Nope

**Comment by tommach591** [comment]
Hi, I am interested in working on this issue for GSoC 2023.

Just to clarify, are we supposed to have only 2 waypoints by default instead of the current 3?

**Comment by nilsnolde** [comment]
It was solved in #66
