### ISSUE TITLE
GSoC 2023 announcement - HOLD

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#65]
Everyone who’s interested to apply to GSoC 2023:

please wait with contributions until the projects are announced. We’ll update here once we’d like to start the initial candidate coordination.

EDIT: I realized this is having the exact opposite effect I intended :D We appreciate your enthusiasm! It's good to express your interest here. But please hold off with PRs to not waste your own time. We will soon announce how to organize the candidate selection. Only selected candidates will be required to put in a PR. So please, no pull requests if you're interested.

**Comment by FLYERVIVEK** [comment]
Let me kick this off!!

I am Vivek, a Sophomore at Chandigarh University pursuing my bachelor's degree in computer science and technology. I have been actively involved with Web Development for past 3 months now working on polishing of my skills with relevant and renowned Organisations . I have always been passionate about the time complexity/ making a code more flexible and efficient.  I am looking forward to contribute as a developer and build some amazing webpages. 
Skills - HTML, CSS, JAVASCRIPT, REACT.Js, NODE.Js,  Mongodb, Express.Js
, DSA, Python, JAVA,

**Comment by hs7898753** [comment]
Hi! My name is Harsh Sharma, and I'm interested in contributing to your open-source project. I'm new to open-source development, but skilled in HTML, CSS, JavaScript, DSA, and React.

I'm eager to learn and contribute to meaningful projects that align with my skills and interests. Your project caught my attention, and it would be an excellent opportunity for me to grow as a developer and contribute to the community.

Please guide me on how I can start contributing to your project. Please let me know if there are any specific areas or issues where I can help.

**Comment by aa98-45556443355666** [comment]
Hello Everyone, I am Aarush Choubey currently pursuing B.Tech in Mechanical Engineering from NIT Hamirpur, India. I have worked with JavaScript,Node.js, React.js, MongoDB. I am deeply motivated and excited to start my journey in open-source contributions. I am interested in working with OpenStreetMap  and I want to contribute to the proposed idea for GSOC 2023. Can any mentor can guide me that from where I should start and what should be my steps in order to get selected in GSOC 2023 program. Your idea list of GSOC 2023 caught my concentration and  it would be an magnificent opportunity for me to learn and grow as a developer. Please guide me that how I can   connect with the assigned mentors of the project.

**Comment by brandon-nguyen-lam** [comment]
Hi! My name is Brandon Lam and I'd love to contribute to this project. I'm rather new to open-source but I am skilled in designing and executing interfaces with Figma, React, React Native, JavaScript/TypeScript, and HTML/CSS. After checking the Valhalla web application, I managed to find a couple of improvement points and wrote down some possible solutions to them. I also found an issue on the mobile page and I will try to create a fix for that tomorrow and make a PR.

I'm excited to start my open-source journey with you guys!

**Comment by ksba2004** [comment]
Hello Everone, I am Aryan Garg and I am a sophomore pursuing my Bachelors in Electronics and Communicaion branch. I would like to contribute to the Valhalla-app and I am interested in the project namely: " Improve Valhalla's React App".
My profficient skills are HTML, CSS, Javascript, ReactJS.
Can anyone please guide me on how do I get started?

**Comment by kanishk6103** [comment]
Hey people, I am Kanishk Tiwari and I am pursuing my BTech degree in Information Technology. I would love to start my open source journey with OpenStreetMaps and would like to contribute to the valhalla app, I have worked with HTML, CSS, Javascript and React, apart from this I have also worked with designing UI/UX for a few websites using Figma and AdobeXD.

**Comment by inceptionabhishek** [comment]
Hi, @nilsnolde 
I am Abhishek. I am very interested and curious to work on and explore this project. I would love to participate in Gsoc 2023 with this project. I am 3rd Year Computer science student. And I have 7 months of experience working at start-ups writing production-ready codes. I am currently going through issues in this project and finding new ones, I will definitely make a pull request if I solve one. Thanks 🤎

**Comment by Apurv428** [comment]
Hello, 

My name is Apurv Sonawane. I'm a third-year undergraduate studying Electronics Engineering at VJTI, Mumbai, India.
I'm quite interested in applying to improve Valhalla's Web App. I've pretty good experience with front-end technologies along with the front-end framework React.Js. I've two years of experience working on the front-end part and have also done a front-end internship at a budding startup. I'm passionate about making the code more efficient and easy to understand along with keeping in mind the needs of the user. I'm looking forward to contribute to OpenStreetMap.

Attaching a link to my [GitHub](https://github.com/Apurv428), [LinkedIn](https://www.linkedin.com/in/apurvsonawane/), and [Resume ](https://drive.google.com/file/d/1mTHD2tlf_esFU1OfImuUVrwQPhBjhSrv/view?usp=sharing)for your convenience.

Thank You.

**Comment by nilsnolde** [comment]
See #67
