### ISSUE TITLE
GSoC 2023 - README!

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/valhalla-app#67]
Let's try this again:

**READ AND FOLLOW THIS CAREFULLY IF YOU WANT TO BE CONSIDERED**

We highly appreciate the volume of people who want to be considered for our project idea for GSoC 2023. However, please **hold off raising PRs**. There is an application process behind GSoC and we will follow it. You will be notified when the application process for contributors is opened (either by us and/or Google) and **only then** should you apply. 

We will close any PRs which will be opened after this issue and will not consider the person raising it. Consider it a first test.

**Comment by nilsnolde** [comment]
I wrote down a few things which should be followed this year for GSoC:

https://github.com/gis-ops/valhalla-app/wiki/GSoC-2023

Good luck!

**Comment by nilsnolde** [comment]
For anyone having open PRs: I'll get to them soon, likely on the weekend. Already thanks for taking care of so many issues! 

Best if everyone subscribes to this issue so you updates when some more info becomes available.

**Comment by AFZL210** [comment]
I have a question regarding discussions. Is there any public channel for contributors?

**Comment by nilsnolde** [comment]
So, for the proposal, I'd suggest to focus on:
- testing end-to-end including a Github Actions workflow which runs on PRs, so that the most important functionality is preserved. This might need a bit of more setup, e.g. getting a local Valhalla setup on Github Actions. Explicitly, we **don't want unit tests**, it's an unnecessary burden for the project (remember, after GSoC is gone, it'll still mostly be me who's maintaining all this..)
- re-write using functional components instead of class-based as now. Don't worry about the exact design/architecture of it for now, it's part of the project 
- being able to link/integrate better to openstreetmap.org, including, but not limited to (own suggestions welcome):
  - a tool button to jump to the same map extent as currently active
  - re-create a route on openstreetmap.org for the active profile (note, not all profiles are supported for Valhalla on osm.org)
  - include an entry in the left-click menu to call Valhalla's `/locate` endpoint to retrieve the OSM ID of the way being clicked on so we can see the way's properties on osm.org (first `/locate` result is enough, as there might be many edges being returned)

**Comment by AdamJamiu** [comment]
HI @nilsnolde I would love to work **_re-create a route on openstreetmap.org for the active profile (note, not all profiles are supported for Valhalla on osm.org)_**. please how can i get started 😊

**Comment by nilsnolde** [comment]
Sorry, gotta be strict here: that will be part of the GSoC project.

**Comment by KASOZIDENIS** [comment]
Thank you so much for the info Nil

**Comment by hemanthpidugu** [comment]
Hi nilsnolde, How can I contribute? this is my first time contributing to an open source.

**Comment by hemanthpidugu** [comment]
> Hi nilsnolde, How can I contribute? this is my first time contributing to an open source.



> Hi nilsnolde, How can I contribute? this is my first time contributing to an open source.

are there any list of issues so that I can pick one?

**Comment by hs7898753** [comment]
> > Hi nilsnolde, How can I contribute? this is my first time contributing to an open source.
> 
> > Hi nilsnolde, How can I contribute? this is my first time contributing to an open source.
> 
> are there any list of issues so that I can pick one?

Checkout Issues Section. It contain many issues you can work on.

**Comment by nilsnolde** [comment]
I'd appreciate if everyone wouldn't always quote the entire previous comment in their answer, let alone duplicate a comment.. It produces tons of digital waste and makes it really hard to focus on the topic.

**Comment by Ananya2001-an** [comment]
Yes you are right. In some cases it really becomes difficult to read.

**Comment by marcelrm11** [comment]
Hello, I am interested in collaborating to the project. I just knew about GSoC, so I didn't have the time to properly do the research and/or collaborate to open issues. Is there any possibility I might be considered a serious candidate? Thanks

**Comment by Ruthvik2707** [comment]
Hello, After reviewing some of the documents, I learned you are developing an application that calculates and shares geodata. The problem for this kind of application is a friendly user interface that is not complicated I am a react,three.js frontend developer I have a few ideas on how can we achieve this. Here are some ideas 
1)Even the top maps application like google maps suffer to exactly point out the direction that a user need to go so my simple solution would be a 360 view of the user
2)More and More features keep getting added to the kind of applications so we need to make a self-sustaining application that is easy to maintain 
if you want to know about me visit https://ksruthvik.com I would like to work with you guys. This is my first time so I will wait for the reply before I make a proposal

**Comment by nilsnolde** [comment]
Sorry people, we have already a lot of applicants who were contributing for the past weeks, some even the past months.

**Comment by nilsnolde** [comment]
So, we had a review meeting with the OSM group and were voting which projects make the cut. Unfortunately the web app didn't make it.. Thanks to everyone contributing over the past months. It really took a lot of time on my end as well, but I think the web app got a lot better with all your contributions. Special thanks to (in no particular order) @hs7898753 @Ananya2001-an @harsh5902 @Sheikh-JamirAlam
