### ISSUE TITLE
add unit test cases for every react component in Jest

### ISSUE THREAD

**Issue by deepchauhan** [gis-ops/valhalla-app#72]
I would like to write unit test cases for the react components in Jest, and achieve a good code coverage. With unit testing, we can have more control over their individual code block quality before integrating different components. Also, it is easier to identify and rectify mistakes or defects at the code level.

**Comment by nilsnolde** [comment]
You’re absolutely right! But: we won’t be able to maintain unit tests in the long run. #58 is good enough for our purposes.
