### ISSUE TITLE
feat: format downloaded JSON file

### ISSUE THREAD

**Issue by Ananya2001-an** [gis-ops/valhalla-app#75]
**Problem**
Currently the json files are not well formatted which reduces readability and understandability.   

**Solution**
We can use an npm package 'json-format' to format the files with proper spaces.

**Screenshots**
 right now
![sddsd](https://user-images.githubusercontent.com/55504616/222373604-c464a704-8369-4d1e-a47a-7e601e4805ec.jpg)

after formatting
 
![Screenshot 2023-03-02 135343](https://user-images.githubusercontent.com/55504616/222373656-f69a06a4-0427-4f1a-8048-58e1ae537a21.jpg)

**Comment by Ananya2001-an** [comment]
I have already solved the issue. If it's approved I will raise a PR.

**Comment by nilsnolde** [comment]
Thanks for the suggestion. I was about to decline (more dependencies, the triviality of making it human-readable etc), but maybe you're right, it's more convenient and in the spirit of what the export is supposed to do for a user.

Happy to have the PR, thanks. This is GSoC related I assume?

**Comment by Ananya2001-an** [comment]
> Thanks for the suggestion. I was about to decline (more dependencies, the triviality of making it human-readable etc), but maybe you're right, it's more convenient and in the spirit of what the export is supposed to do for a user.
> 
> Happy to have the PR, thanks. This is GSoC related I assume?

Thanks for approving @nilsnolde. I will raise a PR soon. Yes I am willing to make a proposal for GSOC when the application period begins.
