### ISSUE TITLE
SliderValue issue

### ISSUE THREAD

**Issue by Ghat0tkach** [gis-ops/valhalla-app#77]
Whenever we do some change in ***Extra Settings*** using **Slider** , the value gets output in the javascript console which in turn makes the app a bit slow. Before raising this issue, I went thoroughly through the codebase to check whether this is done intentionally or not.
##

![Screenshot (52)](https://user-images.githubusercontent.com/59855919/222478031-5b8d8893-e0a5-43d9-b3b7-039d7fa514b4.png)

## Suggested fix
it's a simple fix, we have to remove or comment on the console.log(SliderVal) from the code, this will resolve the issue.

**Comment by nilsnolde** [comment]
Yeah that was annoying me since ages too.. But apparently never enough to go and look for the issue :sweat_smile:

**Comment by Ghat0tkach** [comment]
Is it okay if i add this into my already raised PR? Or its a simple issue could be solved by anyone , more preferably to the people who are beginner and would love to contribute in this project :)

**Comment by nilsnolde** [comment]
> Is it okay if i add this into my already raised PR

Yeah totally, thanks!
