### ISSUE TITLE
fix: showing results for respective tab

### ISSUE THREAD

**Issue by Ananya2001-an** [gis-ops/valhalla-app#78]
**Problem**
Right now even if we have switched to the isochrones tab, we are still showing results of the directions tab at the bottom. After entering name of a place for which we want to generate an isochrone we don't know that the results are at the bottom of the sidebar below the results of directions. This is not very convenient for users.

**Solution**
We can show the results depending upon the respective tab that has been chosen.     

**Screenshot**
https://user-images.githubusercontent.com/55504616/222498026-b86acf99-0f28-4403-99b5-9ac2c6541818.mp4

**Additional note**
I can work on this.

**Comment by nilsnolde** [comment]
Hm, to be honest, I consider this more of a feature. I remember we did that intentionally. The idea is that you don't lose the directions result once you calculate an isochrone. It's also there for sanity checks of the routing & isochrone algorithm: you do an isochrone, then a route from its center to the edge of the isochrone should show pretty much the same time.

I think you have a _very_ small screen/low resolution? What we could do is switch the vertical order of the results depending on the active tab? Would that be more convenient you think?

**Comment by Ananya2001-an** [comment]
> Hm, to be honest, I consider this more of a feature. I remember we did that intentionally. The idea is that you don't lose the directions result once you calculate an isochrone. It's also there for sanity checks of the routing & isochrone algorithm: you do an isochrone, then a route from its center to the edge of the isochrone should show pretty much the same time.

Got it 

> I think you have a _very_ small screen/low resolution? What we could do is switch the vertical order of the results depending on the active tab? Would that be more convenient you think?

Yeah that sounds better :) Shall I raise a PR for that?

**Comment by nilsnolde** [comment]
Sure, if you like. Thanks!
