### ISSUE TITLE
fix: React.KeyboardEvent Error in Waypoint.jsx

### ISSUE THREAD

**Issue by eshan-003** [gis-ops/valhalla-app#80]
Waypoint.jsx include the React.KeyboardEvent Error. Which can be solved if we remove it and only pass event .
Error:-
![Screenshot 2023-03-03 19 39 59](https://user-images.githubusercontent.com/107420267/222744859-8d1bca0e-7433-4235-acee-4f36adf1443e.png)
Fix:-
![Screenshot 2023-03-03 19 50 10](https://user-images.githubusercontent.com/107420267/222744953-f6bf0adb-1577-4015-acb9-ed02ad3574fd.png)

Hope this helps.
Can i create a pull request for it?

**Comment by nilsnolde** [comment]
You sure that’s the only thing you want to fix with the one issue you’ll get?

**Comment by eshan-003** [comment]
yeah i found the same error in index.jsx in Isochrones/Waypoints.jsx.Would like to fix that too? Should i raise the PR

**Comment by Ananya2001-an** [comment]
This issue is already fixed here #83 We should close it.
