### ISSUE TITLE
prettier/prettier error in the application

### ISSUE THREAD

**Issue by harsh5902** [gis-ops/valhalla-app#82]
Getting such errors in the application.
![image](https://user-images.githubusercontent.com/74867899/222795434-515f7038-2df9-492c-8266-331d19093683.png)

Fixed the error:
![image](https://user-images.githubusercontent.com/74867899/222796836-7d9cfdbd-38bf-4541-b334-138161c59638.png)

**Comment by harsh5902** [comment]
I have already solved the issue kindly assign it to me.

**Comment by nilsnolde** [comment]
Getting rid of linking errors is always good. Are those the only ones that pop up though?

**Comment by harsh5902** [comment]
Yes, this was the only ones that would pop up as error
Yes, whenever the application used to start I would get these error.

Shall I open a pull request??

**Comment by nilsnolde** [comment]
If you think it's worth it, sure.

**Comment by nilsnolde** [comment]
Sorry, I just get the issue (I hardly every work with JS). Are you using a different configuration than the default? What's your npm/node version? I'm not getting this errors.

**Comment by harsh5902** [comment]
Yes, I made changes in the prettierrc.json file as I was getting this error continuously after starting the web app. So, I fixed it with the thought that many could be facing such error.

**Comment by nilsnolde** [comment]
But why is no one else getting this error? Do you possibly have a global `prettier` package installed and not in local `node_modules`? If so, that'd be a bad idea.

**Comment by aa98-45556443355666** [comment]
I am also getting the same prettier error on opening the web application.

**Comment by nilsnolde** [comment]
And you have which prettier version installed? `prettier -v`?

**Comment by Ghat0tkach** [comment]
im not getting any prettier error ,

**Comment by nilsnolde** [comment]
Might be Windows related? It's weird that it's complaining on every line, so makes me think it's somehow line ending related (POSIX vs Windows shit)..

**Comment by nilsnolde** [comment]
If you're on Windows then you have git misconfigured maybe?

**Comment by Ghat0tkach** [comment]
i am using windows 11, not getting this error , i ran this web application using the not -so traditional method by downloading zip without having git configurations. It worked perfectly . This error might be caused due to improper installations of npm i beleive so.

**Comment by nilsnolde** [comment]
Hm, not sure how npm can have smth to do with it? If it was somehow "improper" it'd be broken. It could be an old version, but also that wouldn't show in this way I'm very sure. Also my theory is not very sound.. Why would it only be one file if it's a Windows git misconfig for the line ending checkout/push..

No idea and hard to tell without more info. In any case, it's more smth belonging to stackoverflow.com or so, as it's clearly working for the majority.

**Comment by aa98-45556443355666** [comment]
> And you have which prettier version installed? `prettier -v`?

Its **"prettier": "^2.7.1"** version.

**Comment by nilsnolde** [comment]
> Do you possibly have a global prettier package installed and not in local node_modules? If so, that'd be a bad idea.

Well then this is correct.. This project uses 2.8.4. Don't install global packages, esp linting stuff, it's asking for trouble.

**Comment by aa98-45556443355666** [comment]
> > Do you possibly have a global prettier package installed and not in local node_modules? If so, that'd be a bad idea.
> 
> Well then this is correct.. This project uses 2.8.4. Don't install global packages (EDIT: for dev at least, it's ok to install executable to be used from npm but never dev dependencies!), esp linting stuff, it's asking for trouble.

Now the problem is solved. Thanks for giving the correct method.

**Comment by nilsnolde** [comment]
Hm sorry, what you were writing is the semantic minimum version. Is that really your version? I mean I can read this package.json, but I can't execute `npm --version` in **your** environment. 

Now, it is possible that you installed this repo (and its deps) ages ago when prettier was still at 2.7.1 on npm and in the meantime we introduced some crap that's not compatible with 2.7.1 anymore, but I highly doubt that. 

So, again, it's most likely the prettier version you have installed.. `which prettier` should point to your _local_ `node_modules`.
