### ISSUE TITLE
buttons-replacement module

### ISSUE THREAD

**Issue by ashavijit** [gis-ops/valhalla-app#84]
the zoom-in zoom-out and other buttons can be replaced to any side of screen.
`Reason`
`If someone is searching a place that appears just under the button then the user might needs to replace the button`

**Comment by affan00733** [comment]
Hi , 
I am a working professional and willing to participate in GSOC 2023 so want to solve this issue

**Comment by ashavijit** [comment]
I am here to do so

**Comment by nilsnolde** [comment]
This doesn't really make to me, can you explain properly please?

**Comment by ashavijit** [comment]
> This doesn't really make to me, can you explain properly please?

i thinks implementing a feature in which zoom buttons can be replacable i.e hold and dragable

**Comment by nilsnolde** [comment]
OK, why would you want to do that? I don't see value in this, sorry
