### ISSUE TITLE
Update Directions placeholders

### ISSUE THREAD

**Issue by tommach591** [gis-ops/valhalla-app#86]
One idea I have is replacing the placeholder text in Directions from "Hit enter for search..." to "Starting Point" for the first waypoint and "Destination" for the rest to make it more intuitive for users.

I can work on it for preparation for GSoC.

![Capture](https://user-images.githubusercontent.com/57111473/222941508-95519daf-0b6d-43e1-bc35-df4f14878497.PNG)

**Comment by nilsnolde** [comment]
Hm, sorry, doesn't make much sense IMO. The indices on the left side indicate what it represents and it's pretty intuitive that `1` represents the start point. Also, it's not like 2-4 are destinations! They're via points. The destination is 5.
