### ISSUE TITLE
Same width of Directions and Isochrones

### ISSUE THREAD

**Issue by aaryahjolia** [gis-ops/valhalla-app#88]
![Valhalla_Bug](https://user-images.githubusercontent.com/82600388/222975038-c531943c-f7dc-4cde-ae3a-75005ad0fc4e.png)
  

As seen in above picture, the width distribution is uneven when we switch to Isochrones, the box or the left pane shrinks some what and due to that, The **2**nd section of image shows uneven distribution.

Also, In the **1**st section, We can give 50-50 width to directions and isochrones so they will look much good.
Something like this:
![image](https://user-images.githubusercontent.com/82600388/222975410-de25d6c3-29d8-4066-a8b1-42aa6dc81041.png)

I want to implement and fix both of this issue as a part of my pre-gsoc work.

**Comment by nilsnolde** [comment]
> Also, In the 1st section, We can give 50-50 width to directions and isochrones so they will look much good.
Something like this:

This makes sense to me.

> As seen in above picture, the width distribution is uneven when we switch to Isochrones

Yes, that's annoying. However, I don't see the relation to `The 2nd section of image shows uneven distribution.`

If you want, please PR and I can have a look.
