### ISSUE TITLE
Search location on each key press

### ISSUE THREAD

**Issue by aaryahjolia** [gis-ops/valhalla-app#89]
I was going through the whole code and I saw that the dispatch method to fetch the locations is only dispatched when someone enters 'Enter', What if we can provide the search result on each key press for good user experience?

What's your take on this issue? If this can be solved, I'm happy to solve this as part of my pre-gsoc work.

**Comment by nilsnolde** [comment]
Ah no, what you're suggesting is called "autocomplete" and is violating the [Nominatim geocoder ToS](https://operations.osmfoundation.org/policies/nominatim/#unacceptable-use). There's other OSM based geocoders out there, but none has a public API.
