### ISSUE TITLE
Text besides time icon, breaks the defined size

### ISSUE THREAD

**Issue by aditygrg2** [gis-ops/valhalla-app#91]
Check the images - 
<img width="1440" alt="Screenshot 2023-03-06 at 13 56 21" src="https://user-images.githubusercontent.com/98523623/223061373-54a0b71a-cccd-4e78-8c52-937537ded3aa.png">
<img width="1440" alt="Screenshot 2023-03-06 at 13 56 13" src="https://user-images.githubusercontent.com/98523623/223061434-9d014182-ca44-4480-bc16-2f3dfb6ff1b1.png">

The text besides the time icon, is not in a single line, which distorts UI and doesn't look good.

This can be improved by either shortening the text, for example, min can be written as m, and seconds as s or we can reduce the text size, or give it more space, but the latter one will require more refactoring, and the first one is easy to fix and UI will not be affected much.

If needed, I can solve this issue as my pre-gsoc work.

**Comment by nilsnolde** [comment]
Yeah I agree. In fact let's do the hh:mm:ss format.

**Comment by aditygrg2** [comment]
@nilsnolde There are days defined as well. I think it will be confusing if we keep hh:mm::ss format, a d,h,m,s format will look more better.

**Comment by nilsnolde** [comment]
Yeah I think that was the reason why we did it this way as it could potentially wrap around 24 hours into the next day. I'm fine with your proposal too, still better than currently.

**Comment by aditygrg2** [comment]
Great, thank you, will add a PR!
