### ISSUE TITLE
Small caps texts in Directions and Isochrones profiles

### ISSUE THREAD

**Issue by aditygrg2** [gis-ops/valhalla-app#92]
From a UX perspective, all small caps and big caps are not seen as formal. For the units, it is okay as it is written in all small caps only, but the profiles should have mixed caps (first capital, other small) to improve readability.

<img width="1440" alt="Screenshot 2023-03-06 at 14 21 48" src="https://user-images.githubusercontent.com/98523623/223063514-72fedb65-bab1-4e49-98fb-9259c52c3ea8.png">

I can help with this issue.

**Comment by nilsnolde** [comment]
Hm okay :D Can you merge this with your previous issue and just call it "minor UI improvements"? Only one PR would be appreciated:)
