### ISSUE TITLE
Vertical Scrolling enhancement 

### ISSUE THREAD

**Issue by JA-26-01** [gis-ops/valhalla-app#97]
### Description

Unlike the horizontal scrolling which runs in full circle, ensuring that the user can get back to the same location after a specific number of scrolls horizontally, the same feature is not enabled in vertical scrolling. I think the user experience will be enhanced if the same functionality can be added when the user scrolls vertically instead of reaching a boundary. I think the attached screenshot will help in conveying better what I am trying too suggest. I would like to work on this issue if you think this will be a potential enhancement to the app.

### Screenshots

![image](https://user-images.githubusercontent.com/108082336/223187607-5bd2339b-78e9-4baf-a37a-854a037f8eca.png)

**Comment by nilsnolde** [comment]
Not sure that's doable with web mercator projection? see https://stackoverflow.com/questions/40607963/leaflet-infinite-vertical-scrolling

**Comment by JA-26-01** [comment]
Yes I went through this issue and someone suggested using a customized CSS may help. I will try it out and get back to you soon.
