### ISSUE TITLE
[BUG] Directions Waypoint overflow

### ISSUE THREAD

**Issue by tommach591** [gis-ops/valhalla-app#99]
### Description

List of waypoints extend outside the box.

I think we should make the list of waypoints scrollable instead. I would like to work on it for GSoC.

### Screenshots

![overflow](https://user-images.githubusercontent.com/57111473/223284784-ebce7c9f-0e1a-4338-807e-2850d47b84b2.PNG)

**Comment by Ghat0tkach** [comment]
Oh didn't noticed it , but if we changed the behaviour to scroll then the geocoding results shall also be scrollable .

**Comment by nilsnolde** [comment]
Yep, good point, I agree!

> then the geocoding results shall also be scrollable .

Also good point:) You solved it via z-index right? Maybe it'll override the scroll area?

**Comment by Ghat0tkach** [comment]
> Also good point:) You solved it via z-index right? Maybe it'll override the scroll area?
The z index was already intact , i used the overflow:inherit property to make the child element (search results ) extend vetically. However it also impacted the main parent element.

**Comment by tommach591** [comment]
I made the waypoints scrollable, but I haven't found a solution for the geocoding results yet.

Closest I got was by using position: absolute, but that ruins everything else. I also haven't found a solution using z-index yet.

**Comment by Ghat0tkach** [comment]
I do have an idea, whenever we click on the add waypoint the parent div class name shall change to "flex flex-column overflow:auto" from "flex flex-column' .
And whenever we click on search it shall revert back to original

**Comment by ankitjangidx** [comment]
> I made the waypoints scrollable, but I haven't found a solution for the geocoding results yet.
> 
> Closest I got was by using position: absolute, but that ruins everything else. I also haven't found a solution using z-index yet.

why this bug is not visible to me :(
![Screenshot 2023-03-07 143306](https://user-images.githubusercontent.com/100501722/223374375-0c6d82dd-f3ec-4fd4-882a-7a6d43a6af97.png)

**Comment by tommach591** [comment]
When you search for a location, the search results also become scrollable.

![Capture](https://user-images.githubusercontent.com/57111473/223541084-2cec30b1-27e3-4854-babb-4b98fc08f827.PNG)

We want the search results to not be part of the scrolling.

![Capture2](https://user-images.githubusercontent.com/57111473/223541388-2e83ab9e-65c5-43d4-880b-31497c89f90d.PNG)

**Comment by ankitjangidx** [comment]
> > > I made the waypoints scrollable, but I haven't found a solution for the geocoding results yet.
> > > Closest I got was by using position: absolute, but that ruins everything else. I also haven't found a solution using z-index yet.
> > 
> > 
> > why this bug is not visible to me :( ![Screenshot 2023-03-07 143306](https://user-images.githubusercontent.com/100501722/223374375-0c6d82dd-f3ec-4fd4-882a-7a6d43a6af97.png)
> 
> When you search for a location, the search results also become scrollable.
> 
> ![Capture](https://user-images.githubusercontent.com/57111473/223541084-2cec30b1-27e3-4854-babb-4b98fc08f827.PNG)
> 
> We want the search results to not be part of the scrolling.
> 
> ![Capture2](https://user-images.githubusercontent.com/57111473/223541388-2e83ab9e-65c5-43d4-880b-31497c89f90d.PNG)

new bug:/
![image](https://user-images.githubusercontent.com/100501722/223702565-d18940b9-5699-4dc1-b8af-4785611effd8.png)
